version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
  backend:
    build: .
    depends_on:
      - mongodb
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=${PROFILE}

volumes:
  mongodata:
